// ESLint 9 flat config.
//
// Scoped deliberately narrowly: this project's correctness is enforced by the
// TypeScript compiler in strict mode and by the test suite, so lint is here for
// the things neither of those catches — an unused export drifting out of use, a
// floating promise in a worker, an `any` quietly widening a typed boundary.
// Rules that merely restate what `tsc --strict` already rejects are left out.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/coverage/**',
      'packages/db/src/generated/**',
      // Generated by Next on every build; not ours to satisfy.
      'apps/web/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // Prefixing with _ is the established way to say "deliberately unused".
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // `any` is the one that actually costs something: it silently disables
      // every other guarantee downstream of it.
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': ['error', { allow: ['error'] }],
      eqeqeq: ['error', 'smart'],
      // Off deliberately: it fires on `let x = ''` that both branches then
      // overwrite. The initializer is what keeps the variable definitely
      // assigned for the compiler, so "useless" is the wrong reading.
      'no-useless-assignment': 'off',
    },
  },
  {
    // Seeds and CLI wrappers exist to print to a terminal, and plain .mjs files
    // are not covered by the TypeScript globals, so declare the Node ones.
    files: ['packages/db/src/seed.ts', '**/*.mjs', 'scripts/**'],
    languageOptions: { globals: { process: 'readonly', console: 'readonly' } },
    rules: { 'no-console': 'off' },
  },
  {
    // Tests reach into internals and construct deliberately malformed input.
    files: ['**/*.test.ts', 'test/**'],
    rules: { '@typescript-eslint/no-explicit-any': 'off', 'no-console': 'off' },
  },
);
