/**
 * AGENT 11 — MEDIA SOURCING.
 *
 * Finds imagery for content, and — the part that actually matters — attaches
 * the provenance that lets the rights agent make a decision about it.
 *
 * The brief's rule is that public accessibility is not a licence. So this agent
 * has exactly two legitimate routes: generate the image ourselves, or take it
 * from a provider whose licence terms we can record. There is no third path
 * that fetches an arbitrary image from the web, because there would be no
 * defensible answer to "may we publish this commercially?"
 *
 * Priority order, and why:
 *   1. GENERATED  — unambiguous rights, no attribution burden, and it can be
 *                   directed to the brand's visual register rather than merely
 *                   matched to it.
 *   2. STOCK      — real photography, licensed for commercial use, but carries
 *                   an attribution obligation the publisher must honour.
 *   3. NONE       — the brand background. A legitimate editorial look, not a
 *                   failure, which is why a missing image never blocks a post.
 */
import { type Logger } from '@mmos/core';
import type { ImageProvider, StockImage, StockImageProvider } from '@mmos/ai';
import type { AssetRightsInput } from '../qa/rights.js';

export type SourcedOrigin = 'GENERATED' | 'STOCK_LICENSED' | 'NONE';

export interface SourcedImage {
  origin: SourcedOrigin;
  /** Bytes when generated; absent for stock, which is fetched by URL. */
  data?: Buffer;
  /** Remote URL when the image comes from stock. */
  remoteUrl?: string;
  mimeType: string;
  width?: number;
  height?: number;
  costUsd: number;
  /** Everything the rights agent needs. Never partially populated. */
  rights: AssetRightsInput;
}

export interface MediaSourcingDeps {
  image: ImageProvider | null;
  stock: StockImageProvider[];
  logger: Logger;
}

export interface SourcingRequest {
  /** What the writer asked to be shown, in plain language. */
  visualDirection: string;
  /** Search terms for stock; derived from the topic when absent. */
  keywords?: string[];
  width?: number;
  height?: number;
  /** Skips generation, e.g. when the image budget for a piece is spent. */
  preferStock?: boolean;
}

/** Keeps generated imagery inside the brand's visual register. */
export function buildImagePrompt(visualDirection: string): string {
  return (
    `${visualDirection}. Editorial photography for a premium men's business magazine. ` +
    `Dramatic directional lighting, deep shadows, muted desaturated palette with warm gold ` +
    `highlights. Cinematic, restrained, expensive. No text, no words, no logos, no watermarks.`
  );
}

/**
 * Stock search terms.
 *
 * The visual direction is written for a human ("a dark boardroom at night,
 * shot from the doorway"), which stock search engines handle poorly. Concrete
 * nouns retrieve far better than a full sentence.
 */
export function buildStockQuery(visualDirection: string, keywords: string[] = []): string {
  const stopWords = new Set([
    'a', 'an', 'the', 'of', 'in', 'on', 'at', 'to', 'from', 'with', 'and', 'or',
    'shot', 'image', 'photo', 'picture', 'showing', 'depicting', 'that', 'this',
    'style', 'looking', 'view', 'close', 'up', 'wide', 'angle',
  ]);

  const fromDirection = visualDirection
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]/gu, ' ')
    .split(/\s+/)
    .filter((word) => word.length > 3 && !stopWords.has(word));

  // Keywords first: they name the actual subject, while the visual direction
  // mostly describes treatment.
  return [...keywords.slice(0, 2), ...fromDirection.slice(0, 4)].join(' ').trim();
}

export class MediaSourcingAgent {
  constructor(private readonly deps: MediaSourcingDeps) {}

  /**
   * Sources one image. Never throws for want of a picture: a piece without
   * imagery is still publishable, so failures degrade to the brand background
   * rather than taking the content down with them.
   */
  async source(request: SourcingRequest): Promise<SourcedImage> {
    const width = request.width ?? 1024;
    const height = request.height ?? 1792;

    if (this.deps.image && !request.preferStock) {
      try {
        const [generated] = await this.deps.image.generate({
          prompt: buildImagePrompt(request.visualDirection),
          width,
          height,
        });
        if (generated) {
          return {
            origin: 'GENERATED',
            data: generated.data,
            mimeType: generated.mimeType,
            width: generated.width,
            height: generated.height,
            costUsd: generated.costUsd,
            rights: {
              assetSource: 'GENERATED',
              license: `Generated by ${generated.model}`,
              attributionRequired: false,
            },
          };
        }
      } catch (err) {
        this.deps.logger.warn({ err }, 'image generation failed; falling back to stock');
      }
    }

    const query = buildStockQuery(request.visualDirection, request.keywords ?? []);
    for (const provider of this.deps.stock) {
      try {
        const results = await provider.search(query, {
          limit: 5,
          // Carousels are 4:5 and reels 9:16, so a landscape crop wastes the canvas.
          orientation: height > width ? 'portrait' : 'landscape',
        });
        const best = pickBest(results, width / height);
        if (!best) continue;

        // Required by Unsplash's API terms whenever an image is used.
        await provider.trackUsage?.(best);

        return {
          origin: 'STOCK_LICENSED',
          remoteUrl: best.url,
          mimeType: 'image/jpeg',
          width: best.width,
          height: best.height,
          costUsd: 0,
          rights: {
            assetSource: 'STOCK_LICENSED',
            sourceUrl: best.sourceUrl,
            license: best.license,
            creator: best.creator,
            attributionRequired: best.attributionRequired,
            attributionText: best.attributionText,
          },
        };
      } catch (err) {
        this.deps.logger.warn({ err, provider: provider.name, query }, 'stock search failed');
      }
    }

    this.deps.logger.info(
      { query },
      'no imagery sourced; the slide will render on the brand background',
    );
    return {
      origin: 'NONE',
      mimeType: 'image/jpeg',
      costUsd: 0,
      rights: { assetSource: 'BRAND_ASSET', attributionRequired: false },
    };
  }
}

/** Prefers the closest aspect ratio, so less of the image is cropped away. */
function pickBest(images: StockImage[], targetRatio: number): StockImage | undefined {
  if (images.length === 0) return undefined;
  return [...images].sort((a, b) => {
    const aDelta = Math.abs(a.width / a.height - targetRatio);
    const bDelta = Math.abs(b.width / b.height - targetRatio);
    return aDelta - bDelta;
  })[0];
}

/**
 * Collects the attribution a published post owes.
 *
 * Attribution is a licence condition, so it has to reach the caption rather
 * than sit unread in the database. The rights agent already blocks an asset
 * whose attribution is required but missing; this is how it gets satisfied.
 */
export function collectAttributions(assets: AssetRightsInput[]): string[] {
  return [
    ...new Set(
      assets
        .filter((asset) => asset.attributionRequired && asset.attributionText)
        .map((asset) => asset.attributionText as string),
    ),
  ];
}
